FROM python:3.9.9-alpine3.14

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade -r requirements.txt
COPY . .
CMD ["uvicorn", "usr.src.app.main:app", "--host", "0.0.0.0", "--port", "80"]
